apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gfdcp0kf3-nodejs 
  janus-idp.io/tekton: gfdcp0kf3-nodejs
  backstage.io/kubernetes-id: gfdcp0kf3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gfdcp0kf3-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml