apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gfdcp0kf3-nodejs
  janus-idp.io/tekton: gfdcp0kf3-nodejs
  backstage.io/kubernetes-id: gfdcp0kf3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gfdcp0kf3-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
